services:
  postgres:
    image: postgres:13.4-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - src/core/.env

  nginx:
    image: nginx:1.20
    ports:
      - "80:80"
    volumes:
      - ./src/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - auth_api

  auth_api:
    container_name: auth_api
    build:
      context: src
    restart: always
    depends_on:
      - postgres
      - redis
    ports:
      - 8000:8000
    env_file:
      - src/core/.env
    entrypoint: >
      sh -c " python3 /src/services/wait_for_postgres.py
      && alembic upgrade head
      && gunicorn wsgi_app:app -b 0.0.0.0:8000 -w 2 --log-level debug --timeout 0"

  redis:
    container_name: redis_container
    image: redis:6.2.6

volumes:
  postgres_data: