services:
  postgres:
    image: postgres:13.4-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    env_file:
      - src/core/.env

  auth_api:
    container_name: auth_api
    build:
      context: src
    restart: always
    depends_on:
      - postgres
      - redis
    ports:
      - 8000:8000
    env_file:
      - src/core/.env
    entrypoint: >
      sh -c " python3 /src/services/wait_for_postgres.py
      && alembic upgrade head
      && gunicorn wsgi_app:app -b 0.0.0.0:8000 -w 2 --log-level debug --timeout 0"

  test:
    container_name: test_api
    build:
      context: tests
    depends_on:
      - postgres
      - redis
    entrypoint: >
      sh -c " python3 /tests/functional/utils/wait_for_redis.py
      && pytest /tests/functional/src -v"

  redis:
    container_name: redis_container
    image: redis:6.2.6
    ports:
      - 6379:6379

volumes:
  postgres_data: